version: '3.8'

services:
  image-deduplicator:
    build: .
    ports:
      - "5010:5010"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data
      - ../stickers_output_20251002_234900:/app/stickers_output
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - STICKERS_OUTPUT_PATH=/app/stickers_output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s